version: '4.3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - '27012:27012'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: locals
